### ISSUE TITLE
:bug: alias addとdeleteが動作しない

### ISSUE THREAD

**Issue by HidemaruOwO** [HidemaruOwO/pummit#16]
### 機能名及び動作

alias add | alias delete

### 再現方法

- add cmd

```bash
$ pummit alias add unko tada
[WARN] Missing alias
```
- delete cmd

```bash
$ pummit alias delete b
panic: runtime error: slice bounds out of range [2:1]

goroutine 1 [running]:
github.com/HidemaruOwO/pummit/pummit/cmd/alias.aliasDelete({0xc00007de50, 0x1, 0x1})
        /home/hidemaru/Code/pummit/pummit/cmd/alias/delete.go:23 +0x306
github.com/HidemaruOwO/pummit/pummit/cmd/alias.AliasDeleteCmd(...)
        /home/hidemaru/Code/pummit/pummit/cmd/alias/delete.go:12
main.main.func3(0xc000197868?)
        /home/hidemaru/Code/pummit/pummit/pummit.go:60 +0x45
github.com/urfave/cli/v2.(*Command).Run(0xc0001c62c0, 0xc0000169c0, {0xc00007ec00, 0x2, 0x2})
        /home/hidemaru/go/pkg/mod/github.com/urfave/cli/v2@v2.25.0/command.go:273 +0x9eb
github.com/urfave/cli/v2.(*Command).Run(0xc0001c6000, 0xc000016840, {0xc0000a74d0, 0x3, 0x3})
        /home/hidemaru/go/pkg/mod/github.com/urfave/cli/v2@v2.25.0/command.go:266 +0xc4d
github.com/urfave/cli/v2.(*Command).Run(0xc0001c69a0, 0xc000016700, {0xc000016080, 0x4, 0x4})
        /home/hidemaru/go/pkg/mod/github.com/urfave/cli/v2@v2.25.0/command.go:266 +0xc4d
github.com/urfave/cli/v2.(*App).RunContext(0xc0001c4000, {0x763298?, 0xc000020068}, {0xc000016080, 0x4, 0x4})
        /home/hidemaru/go/pkg/mod/github.com/urfave/cli/v2@v2.25.0/app.go:332 +0x616
github.com/urfave/cli/v2.(*App).Run(...)
        /home/hidemaru/go/pkg/mod/github.com/urfave/cli/v2@v2.25.0/app.go:309
main.main()
        /home/hidemaru/Code/pummit/pummit/pummit.go:117 +0x736

$ pummit alias delete b r
[WARN] The alias name to be deleted must be added as the third argument
```

### 詳細な情報

config.jsonにはしっかり絵文字エイリアスが存在している

**Comment by HidemaruOwO** [comment]
希望通りに動かないのは与えるargsが足りないため。

https://github.com/HidemaruOwO/pummit/blob/73ecc9aae3a53428c395285188119f9865ae8425/pummit/cmd/alias/add.go#L31..L32

ここをこのように直せば直る

```go
alias := [0]
prefix := [1]
```

**Comment by HidemaruOwO** [comment]
deleteも同じぽい

**Comment by HidemaruOwO** [comment]
引数を指定しないとバグる問題は横着して.Slice()を使ってたからっぽい

**Comment by Comamoca** [comment]
- `alias add`
- `alias delete`
- `pummit prefix message`

のコマンドのコマンドの、

- 引数が渡されていない場合クラシックする問題
- pummitでコミットをした際プレフィックスが適用されない問題

を修正しました。

**Comment by HidemaruOwO** [comment]
領海です。PR通します。
